### ISSUE TITLE
Error on importing posttypes with collection/set fields

### ISSUE THREAD

**Issue by Ornendil** [bobdenotter/conimex#12]
I install a fresh new bolt installation (and a fresh new conimex) and add a posttype like this:
```yaml
tests:
    name: tests
    singular_name: test
    fields:
        tittel:
            type: text
        things:
            type: collection
            fields:
                thing:
                    type: set
                    fields:
                        thing_id:
                            type: text
        slug:
            type: slug
            uses: tittel
```
I fill out a post with some test content and export it with `bin/console conimex:export websitenametest.yaml tests` and get this file:

```yaml
__bolt_export_meta:
    date: '2021-04-05T16:20:17+02:00'
    version: 4.1.17
    platform:
        client_version: 'mysqlnd 7.4.15'
        driver_name: mysql
        connection_status: '127.0.0.1 via TCP/IP'
        server_version: 5.5.5-10.4.11-MariaDB
__users:
    -
        [...]
content:
    -
        id: 1
        contentType: tests
        author:
            id: 1
            username: magnus
        status: published
        createdAt: 2021-04-05T14:29:06+02:00
        modifiedAt: 2021-04-05T14:19:49+02:00
        publishedAt: 2021-04-05T12:29:06+02:00
        depublishedAt: null
        fields:
            things: [{ name: thing, type: set, value: { thing_id: tresters } }, { name: thing, type: set, value: { thing_id: test2 } }]
            slug: soteroen
            tittel: Soteroen
        taxonomies: {  }
        twig: null
        relations: {  }
```

I then try to import it again with `bin/console conimex:import websitenametest.yaml -vvv` and get the following output in the console:

```sh
 ! [NOTE] Importing Bolt database contents from: websitenametest.yaml

^ array:3 [
  "date" => "2021-04-05T16:20:17+02:00"
  "version" => "4.1.17"
  "platform" => array:4 [
    "client_version" => "mysqlnd 7.4.15"
    "driver_name" => "mysql"
    "connection_status" => "127.0.0.1 via TCP/IP"
    "server_version" => "5.5.5-10.4.11-MariaDB"
  ]
]
 // Importing ContentType content

 0/1 [>-------------------------------------------------]   0% < 1 sec/< 1 sec 34.5 MiB
In CollectionField.php line 64:

  [Error]
  Call to a member function setParent() on array


Exception trace:
  at /mnt/c/xampp/htdocs/test/vendor/bolt/core/src/Entity/Field/CollectionField.php:64
 Bolt\Entity\Field\CollectionField->setValue() at /mnt/c/xampp/htdocs/test/vendor/bolt/core/src/Entity/Content.php:500
 Bolt\Entity\Content->setFieldValue() at /mnt/c/xampp/htdocs/test/vendor/bobdenotter/conimex/src/Import.php:184
 BobdenOtter\Conimex\Import->importRecord() at /mnt/c/xampp/htdocs/test/vendor/bobdenotter/conimex/src/Import.php:108
 BobdenOtter\Conimex\Import->importContentType() at /mnt/c/xampp/htdocs/test/vendor/bobdenotter/conimex/src/Import.php:78
 BobdenOtter\Conimex\Import->import() at /mnt/c/xampp/htdocs/test/vendor/bobdenotter/conimex/src/Command/ImportCommand.php:57
 BobdenOtter\Conimex\Command\ImportCommand->execute() at /mnt/c/xampp/htdocs/test/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /mnt/c/xampp/htdocs/test/vendor/symfony/console/Application.php:989
 Symfony\Component\Console\Application->doRunCommand() at /mnt/c/xampp/htdocs/test/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /mnt/c/xampp/htdocs/test/vendor/symfony/console/Application.php:290
 Symfony\Component\Console\Application->doRun() at /mnt/c/xampp/htdocs/test/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /mnt/c/xampp/htdocs/test/vendor/symfony/console/Application.php:166
 Symfony\Component\Console\Application->run() at /mnt/c/xampp/htdocs/test/bin/console:39

conimex:import <filename>
```

If I remove the collection it imports just fine. If I try with a single set instead of a collection I get a very similar error.

# This time with just a set

```yaml
tests:
    name: tests
    singular_name: test
    fields:
        tittel:
            type: text
        sett:
            type: set
            fields:
                thing_id:
                    type: text
        slug:
            type: slug
            uses: tittel
```

```yaml
__bolt_export_meta:
    date: '2021-04-05T16:38:49+02:00'
    version: 4.1.17
    platform:
        client_version: 'mysqlnd 7.4.15'
        driver_name: mysql
        connection_status: '127.0.0.1 via TCP/IP'
        server_version: 5.5.5-10.4.11-MariaDB
__users:
    -
        [...]
content:
    -
        id: 1
        contentType: tests
        author:
            id: 1
            username: magnus
        status: published
        createdAt: 2021-04-05T14:29:06+02:00
        modifiedAt: 2021-04-05T14:38:25+02:00
        publishedAt: 2021-04-05T12:29:06+02:00
        depublishedAt: null
        fields:
            slug: soteroen
            tittel: Soteroen
            sett: { thing_id: test }
        taxonomies: {  }
        twig: null
        relations: {  }
```
```sh
 ! [NOTE] Importing Bolt database contents from: websitenametest.yaml

^ array:3 [
  "date" => "2021-04-05T16:38:49+02:00"
  "version" => "4.1.17"
  "platform" => array:4 [
    "client_version" => "mysqlnd 7.4.15"
    "driver_name" => "mysql"
    "connection_status" => "127.0.0.1 via TCP/IP"
    "server_version" => "5.5.5-10.4.11-MariaDB"
  ]
]
 // Importing ContentType content

 0/1 [>-------------------------------------------------]   0% < 1 sec/< 1 sec 34.5 MiB
In SetField.php line 45:

  [Error]
  Call to a member function setParent() on string


Exception trace:
  at /mnt/c/xampp/htdocs/test/vendor/bolt/core/src/Entity/Field/SetField.php:45
 Bolt\Entity\Field\SetField->setValue() at /mnt/c/xampp/htdocs/test/vendor/bolt/core/src/Entity/Content.php:500
 Bolt\Entity\Content->setFieldValue() at /mnt/c/xampp/htdocs/test/vendor/bobdenotter/conimex/src/Import.php:184
 BobdenOtter\Conimex\Import->importRecord() at /mnt/c/xampp/htdocs/test/vendor/bobdenotter/conimex/src/Import.php:108
 BobdenOtter\Conimex\Import->importContentType() at /mnt/c/xampp/htdocs/test/vendor/bobdenotter/conimex/src/Import.php:78
 BobdenOtter\Conimex\Import->import() at /mnt/c/xampp/htdocs/test/vendor/bobdenotter/conimex/src/Command/ImportCommand.php:57
 BobdenOtter\Conimex\Command\ImportCommand->execute() at /mnt/c/xampp/htdocs/test/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /mnt/c/xampp/htdocs/test/vendor/symfony/console/Application.php:989
 Symfony\Component\Console\Application->doRunCommand() at /mnt/c/xampp/htdocs/test/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /mnt/c/xampp/htdocs/test/vendor/symfony/console/Application.php:290
 Symfony\Component\Console\Application->doRun() at /mnt/c/xampp/htdocs/test/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /mnt/c/xampp/htdocs/test/vendor/symfony/console/Application.php:166
 Symfony\Component\Console\Application->run() at /mnt/c/xampp/htdocs/test/bin/console:39

conimex:import <filename>
```
