### ISSUE TITLE
Simple select field are not importing from Bolt 3 to Bolt 5

### ISSUE THREAD

**Issue by nestordedios** [bobdenotter/conimex#22]
Currently the select field which are being imported are those which have values as referenced content.

Select fields like this are not importing:

```
        cms:
            label: CMS
            type: select
            values:
                'bolt': "Bolt 3"
                'bolt4': "Bolt 4"
                'drupal7': "Drupal 7"
                'drupal8': "Drupal 8"
                'wordpress': "Wordpress"
                'civicrm': "CiviCRM"
                'other': "Other"
```
