### ISSUE TITLE
Error during import of data structure with collection type

### ISSUE THREAD

**Issue by eherber** [bobdenotter/conimex#27]
Running an import of a data structure containing a **collection** results in the following error message:

*Argument 1 passed to Bolt\Repository\FieldRepository::factory() must be an instance of Tightenco\Collect\Support\Collection, null given, called in ... cdu.asbach/vendor/bolt/core/src/Controller/Backend/ContentEditController.php on line 371*

The export has been created with **app/nut database:export**. The import is done by **conimex version 1.3.5**. However the same error occurs with conimex version 2.0.

Enclosed you will find the  **contenttypes.yaml** defintion file for the custom datatype "eingangsseite" and the 
[conimex.support.tar.gz](https://github.com/bobdenotter/conimex/files/7027868/conimex.support.tar.gz)
**eingangsseite.export.yaml** file.

Thank you in advance.

-Eric

**Comment by michaelborn** [comment]
I get the same error reported above.

Here's the snippet of a `page` contenttype showing the `gallery` repeater (now collection).

```yml
gallery:
            - { image: { file: 2019-02/screen-shot-2019-02-09-at-10.28.15-pm.png, title: '' }, html: '' }
            - { image: { file: 2019-02/1549769601_screen-shot-2019-02-09-at-10.25.51-pm.png, title: '' }, html: '' }
```

Here's my Bolt 5 `contenttypes.yaml` definition for the `gallery` field on a `page` contenttype:

```yml
gallery:
            type: collection
            limit: 10
            prefix: "<p>Upload multiple images to create a photo gallery</p>"
            fields:
                slide:
                    type: set
                    fields:
                        image:
                            type: image
                            extensions: [ gif, jpg, png ]
                            attrib: title
                        html:
                            type: html
                            height: 150px
```

Are we simply missing the `set` definition?
