### ISSUE TITLE
ContentType not found by name

### ISSUE THREAD

**Issue by michaelborn** [bobdenotter/conimex#42]
Here's my `contenttypes.yaml` definition for the `articles` content type:

```yml
articles:
    name: Blog
    slug: blog
    singular_name: Article
    singular_slug: blog
    fields:
        title:
...
```

Now, I have an export from a Bolt 3 site with the above content type :point_up: , and I get the error `Requested ContentType articles is not defined in contenttypes.yaml`.

Here's the relevant bits from the export:

```yml
articles:
    -
        slug: new-site-update
        title: New Site Update!
 ...
```

Is the export wrong? (Not a conimex issue) Or should conimex look for contenttypes by the definition name, not by the slug?
