### ISSUE TITLE
Bolt 3 user roles do not translate to Bolt 5 roles

### ISSUE THREAD

**Issue by michaelborn** [bobdenotter/conimex#44]
One thing I noticed on my import of Bolt 3 data to a Bolt 5 site is my user seems to be lacking the admin permissions I was used to on the Bolt 3 site.

Here's my import data, obfuscated of course. :smile: 

```yml
__users:
    -
        id: 1
        username: bornm
        password: pbfuscated
        email: ...
        displayname: bornm_master
        enabled: true
        roles:
            - root
            - everyone
    -
        id: 2
        username: mnawrocki
        password: obfuscated
        email: ...
        displayname: Mike Nawrocki
        enabled: true
        roles:
            - chief-editor
            - root
            - editor
            - admin
            - developer
            - everyone
```

And the assignable roles are (by default) the following:

```yml
assignable_roles: [ROLE_DEVELOPER, ROLE_ADMIN, ROLE_CHIEF_EDITOR, ROLE_EDITOR, ROLE_USER]
```

This isn't a huge deal - I think I can go through my import file and replace `root` with `ROLE_ADMIN`, `editor` with `CHIEF_EDITOR`, etc. The point is this is a "gotcha" from the Bolt 3 upgrade, and it should either be 1) handled seamlessly, or 2) noted in the upgrade docs.
